version: '3'

services:

  web:
    build: .
    links:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    container_name: php
    hostname: php
    links:
      - "db:database"
  db:
    container_name: mongodb
    hostname: mongodb
    image: mongo:4.2
    ports:
      - "27017:27017"
          
